# 9-120 Dockerising Generic Node Apps - (see diagram 9-118/119 for the steps) - for the 'server' (API) Express node.js app
FROM node:alpine
WORKDIR "/app"
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "dev"]
# slightly different default command, in dev environment, for server and for worker, viz for client app
# i.e. to use nodemon ("dev" in package.json), for when the volume is changed ...
# ... because of a host source code change, the container app will be restarted by nodemon

# 'server' and 'worker' Dockerfile.dev are the same in this case