FROM nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf
# file name specified here - overwrite existing file

# 9-127 Building a custom Nginx image - https://hub.docker.com/_/nginx#complex-configuration